export const routesNames = {
  AUTH_STACK: 'AUTH_STACK',
  AUTH_TYPE: 'AUTH_TYPE',
  ONBOARDING: 'ONBOARDING',
  SIGNUP: 'SIGNUP',
  SIGNIN: 'SIGNIN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  HOME: 'HOME',
  REMINDERS: 'REMINDERS',
  ADD_REMINDER: 'ADD_REMINDER',
  EDIT_REMINDER: 'EDIT_REMINDER',
  PROFILE: 'PROFILE',
};
